# Chapter 04 제출 답안 양식. pandas로 데이터에 질문하기

> 주 제출물은 실행 완료 Notebook `chapter04/chapter04.ipynb`입니다. 이 양식의 항목을 Notebook의 Markdown 셀로 추가해 작성합니다.

## 0. 제출 정보
- 이름: 최종인
- GitHub ID: JOGN-IN-01
- 작성일: 2026-10-05
- 최종 제출 URL: https://github.com/JONG-IN-01/llm-data-analysis-study/blob/main/chapter4/chapter4.ipynb

## 1. 질문과 필요한 데이터 선택
### 내가 확인하려는 질문
 어떤 상품 카테코리의 completed 주문 기준 금액이 큰가?

### 사용한 파일/컬럼
 order_items(quantity,unitprice), orders(order_status), products(category)

### 결과 관찰
 각 테이블을 결합하면 가능할 것이다.
 pandas basic.ipynb 파일 코드 기준으로는 스포츠 카테고리가 가장 크다.

### 나의 해석과 판단
 카테고리별 completed 주문 기준 금액을 보려면, 카테고리와 completed 주문, 주문수*개당 가격을 이용하여 총 가격이 필요하기 때문이다.

### 업무·분석적 의미
 카테고리별 주문 기준 금액을 확인하여 어떤 카테고리 상품이 많은 매출을 발생시키는지 알 수 있다.

### 한계와 추가 확인 사항
 카테고리별로 order를 확인하려면 info나 각종 메소드를 이용하여 type과 결측치가 존재하는지 확인할 필요가 있다.

## 2. 필터링·정렬·파생 컬럼
- 적용한 필터 조건: completed 주문만 필터로 걸러내보았다.
- 정렬 기준: 카테고리별로 정렬을 해보았다.
- 만든 파생 컬럼: quantity와 unit_price를 통해 total price를 구해보았다.
- `line_total` 계산식: order_items["line_total"] = (order_items["quantity"]* order_items["unit_price"]

![필터와 파생 컬럼](images/step02_transform_1.png)
![필터와 파생 컬럼](images/step02_transform_2.png)

### 결과 관찰
completed 주문수는 총 184개이다.

### 나의 해석과 판단
어떤 칼럼을 필터의 기준으로 하냐에 따라 추출되는 데이터 다르다. 예를 들어 customer에서 사는 지역으로 필터링을 할 수 있고, age에 따라 필터링을 할 수 있을 것이다.

### 업무·분석적 의미
raw data에서 자신이 추출하고자 하는 데이터를 추출하기 위해 어떤 데이터프레임의 칼럼을 기준으로 필터링을 해야하는지 생각할 필요가 있다.

### 한계와 추가 확인 사항
completed 주문수만 확인했고 completed 주문수와 관련 데이터들은 확인하지 않았다.


## 3. merge 검증
- 병합한 데이터: order_items(left)와 orders(right)
- 사용한 key: order_id
- `validate` 결과: many to one으로 order_items 테이블에 orders 칼럼들이 합쳐졌다.
- `indicator` 결과: both 764 left only 0 right only 0
- 병합 전/후 행 수: 764/764

![merge 검증](images/step03_merge.png)

### 결과 관찰
order_id를 기준으로 order_items와 orders가 merge되었다. 병합 전 후 행수는 변화가 없다.

### 나의 해석과 판단
행수는 증가하지 않았다. merge가 적합하게 되었다고 생각한다. both값도 764이기 때문이다.

### 업무·분석적 의미
잘못된 merge를 하면 결측치가 생길 수 있으며, 또는 행이 늘어나거나 줄어들어 매출이 부풀려지거나 매출이 줄어들 수 있을 것이다.

### 한계와 추가 확인 사항
다른 테이블간의 key 값을 이용하여 merge를 적용해보지 못했다.

## 4. completed 주문 범위와 집계
- 분석 범위 정의: 분석범위는 order_status가 completed인 주문들이다.
- 카테고리별 결과: group으로 집계가 완료되었다.
- 상품별 결과:group으로 집계가 완료되었다.
- 월별 결과:group으로 집계가 완료되었다.
- 고객별 결과:group으로 집계가 완료되었다.

![핵심 집계 결과](images/step04_groupby.png)

### 결과 관찰
26년 8월에 가장 많이 팔렸으며, 카테고리에선 스포츠 카테고리가 상위를 차지하였으며, 이와 비슷하게 상품별 집계에도 상위권에 스포츠 용품들이 다수 존재했다.

### 나의 해석과 판단
카테고리별과 상품별 결과가 가장 중요하다고 생각한다. 어떤 카테고리가 부족하고 그 카테고리에서 어떤 상품이 강세인지 약세인지를 확인할 수 있기 때문이다.

### 업무·분석적 의미
어떻게 마케팅을 할지 어떻게 경영전략을 짤지를 결정할 수 있을 것이다.

### 한계와 추가 확인 사항
회계상 순매출에서는 매출애누리와 포인트 적립 같은 경우 회계 장부상 수익 인식에 있어서 회계상 매출이 아닌 부채로 잡히는 경우가 있기 때문이다.

## 5. 총합 일치 검증
- 원본 completed `line_total` 합계: 148990000
- 카테고리 합계:148990000
- 월별 합계:148990000
- 고객별 합계:148990000
- 차이 여부: 차이가 없다.

![총합 검증](images/step05_total_check.png)

### 나의 해석과 판단
불일치 발생시 코드를 먼저 확인해볼 것이고, 데이터 누락이 있는 지 확인해야할 것이다.

## 6. LLM pandas 코드 검증
- LLM Prompt 요약: 
  orders와 order_items를 사용해
completed 주문 기준 월별 금액을 계산하려고 합니다.

다음을 반드시 포함해 주세요.
- line_total = quantity × unit_price
- orders.order_id 고유성 확인
- many-to-one merge + indicator
- 병합 전후 행 수 확인
- 미매칭 확인
- 날짜 변환 실패 확인
- completed만 필터링
- 월별 total_sales와 고유 order_count 계산
- 결과를 회계상 순매출이라고 단정하지 않기


- 제안 코드 요약: 바로 밑 markdown에 넣었습니다.
- 실제 컬럼/범위와 맞지 않은 부분: 미매칭 확인하는 코드를 추가로 알려주었다. status 칼럼이 raw data에서는 order_status 이다.
- 수정한 내용: completed 주문상태인 행만 필터링 할때 칼럼명을 변경할 필요가 있었다.
- 최종 판단: 수정 후 사용

![LLM 코드 검증](images/step06_llm_validation.png)

### 나의 해석과 판단
LLM 코드가 실행되었다는 것만으로 분석이 맞다고 볼 수 없는 이유를 작성하세요.

## 7. Chapter 04 최종 인사이트
### 가장 의미 있다고 생각한 결과 2가지
1. 정렬,필터링,merge 등 raw데이터를 데이터 분석 전에 해야할 과정을 하나씩 배운 것이 가장 의미있다고 생각한다.
2. group으로 묶어서 각 데이터의 합계가 일치하는지 확인하는 것이 중요하다고 생각한다.

### 그 결과를 뒷받침하는 수치/표
카테고리, 상품, customer, 월별 total 금액이 일치한다.

### 추가로 확인하고 싶은 질문
refunded된 주문의 카테고리또는 상품별 quantity를 조사하여 refund가 많이된 이유를 파악해보고 싶다.

### 현재 결과의 한계
refunded된 주문은 분석하지 않았다.

## 최종 제출 체크
- [O] 핵심 셀 Output이 남아 있습니다.
- [O] merge와 총합 검증 Evidence가 있습니다.
- [O] 결과 관찰과 해석이 구분되어 있습니다.
- [O] LLM 코드를 검증했습니다.
- [O] 개인정보/Secret이 없습니다.
- [O] `chapter04/chapter04.ipynb`가 GitHub에서 정상 표시됩니다.
- [O] 최종 Notebook 파일 URL을 제출합니다.

#LLM 제안코드
import pandas as pd

def calculate_monthly_completed_sales(orders, order_items):
    # 1. orders.order_id 고유성 확인
    if not orders['order_id'].is_unique:
        raise ValueError("오류: orders 테이블의 order_id가 고유하지 않습니다. 중복을 확인하세요.")

    # 2. 날짜 변환 및 변환 실패(NaT) 확인
    orders = orders.copy()
    orders['order_date'] = pd.to_datetime(orders['order_date'], errors='coerce')
    if orders['order_date'].isna().any():
        print(f"경고: 날짜 변환에 실패한(NaT) 데이터가 {orders['order_date'].isna().sum()}건 존재합니다.")

    # 3. line_total 계산 (quantity × unit_price)
    order_items = order_items.copy()
    order_items['line_total'] = order_items['quantity'] * order_items['unit_price']

    # 4. 병합 전 행 수 확인
    rows_before = len(order_items)

    # 5. many-to-one merge 및 indicator 활성화
    # order_items(N)를 기준으로 orders(1)를 병합
    merged_df = order_items.merge(
        orders, 
        on='order_id', 
        how='left', 
        validate='many_to_one', 
        indicator=True
    )

    # 6. 병합 후 행 수 확인
    rows_after = len(merged_df)
    print(f"병합 전 items 행 수: {rows_before} | 병합 후 전체 행 수: {rows_after}")
    if rows_before != rows_after:
        print("경고: 병합 전후의 행 수가 다릅니다. 데이터 중복이나 누락을 확인하세요.")

    # 7. 미매칭 확인
    unmatched_items = merged_df[merged_df['_merge'] == 'left_only']
    if not unmatched_items.empty:
        print(f"경고: orders 테이블에 매칭되지 않은 order_items 데이터가 {len(unmatched_items)}건 존재합니다.")

    # 8. completed 상태만 필터링
    completed_df = merged_df[merged_df['status'] == 'completed'].copy()

    # 9. 월별 total_sales와 고유 order_count 계산
    # 'YYYY-MM' 형태로 월 기간 추출
    completed_df['order_month'] = completed_df['order_date'].dt.to_period('M')
    
    monthly_summary = completed_df.groupby('order_month').agg(
        total_sales=('line_total', 'sum'),
        order_count=('order_id', 'nunique')
    ).reset_index()

    return monthly_summary

# 함수 실행 예시:
# result_df = calculate_monthly_completed_sales(orders_df, order_items_df)
# print(result_df)

In [7]:
from pathlib import Path
import sys

print(sys.executable)
print(Path.cwd())

c:\dev\llm-data-analysis-study\.venv\Scripts\python.exe
c:\dev\llm-data-analysis-study\notebooks

In [8]:
from pathlib import Path


def find_project_root(start: Path) -> Path:
    start = start.resolve()

    for candidate in [start, *start.parents]:
        if (
            (candidate / "data" / "raw").exists()
            and (candidate / "notebooks").exists()
        ):
            return candidate

    raise FileNotFoundError(
        "프로젝트 루트를 찾지 못했습니다. "
        "Notebook을 저장소 안에서 실행해 주세요."
    )


PROJECT_ROOT = find_project_root(Path.cwd())
DATA_DIR = PROJECT_ROOT / "data" / "raw"

print(PROJECT_ROOT)
print(DATA_DIR)

C:\dev\llm-data-analysis-study
C:\dev\llm-data-analysis-study\data\raw

In [9]:
expected_files = [
    "customers.csv",
    "products.csv",
    "orders.csv",
    "order_items.csv",
]

file_check = {
    filename: (DATA_DIR / filename).exists()
    for filename in expected_files
}

file_check

{'customers.csv': True,
 'products.csv': True,
 'orders.csv': True,
 'order_items.csv': True}

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / 'data' / 'raw').exists() and (PROJECT_ROOT.parent / 'data' / 'raw').exists():
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_DIR = PROJECT_ROOT / 'data' / 'raw'
sns.set_theme(style='whitegrid')

print('프로젝트 루트:', PROJECT_ROOT)
print('데이터 폴더:', DATA_DIR)
print('데이터 폴더 존재 여부:', DATA_DIR.exists())

프로젝트 루트: c:\dev\llm-data-analysis-study
데이터 폴더: c:\dev\llm-data-analysis-study\data\raw
데이터 폴더 존재 여부: True

In [11]:
required_files = ['customers.csv', 'products.csv', 'orders.csv', 'order_items.csv']
missing_files = [name for name in required_files if not (DATA_DIR / name).exists()]

if missing_files:
    raise FileNotFoundError(
        '필요한 데이터 파일이 없습니다: ' + ', '.join(missing_files)
        + '. 프로젝트 루트에서 python scripts/generate_sample_data.py를 실행하세요.'
    )

customers = pd.read_csv(DATA_DIR / 'customers.csv')
products = pd.read_csv(DATA_DIR / 'products.csv')
orders = pd.read_csv(DATA_DIR / 'orders.csv')
order_items = pd.read_csv(DATA_DIR / 'order_items.csv')

print('데이터 불러오기 완료')

데이터 불러오기 완료

In [12]:
datasets = {
    'customers': customers,
    'products': products,
    'orders': orders,
    'order_items': order_items,
}

expected_columns = {
    'customers': ['customer_id', 'gender', 'age', 'city'],
    'products': ['product_id', 'product_name', 'category', 'price'],
    'orders': ['order_id', 'customer_id', 'order_date', 'order_status'],
    'order_items': ['order_id', 'product_id', 'quantity', 'unit_price'],
}

for name, df in datasets.items():
    missing = [col for col in expected_columns[name] if col not in df.columns]
    print(name, df.shape, df.columns.tolist())
    if missing:
        raise KeyError(f'{name}에 필요한 컬럼이 없습니다: {missing}')

customers (150, 6) ['customer_id', 'name', 'gender', 'age', 'city', 'signup_date']
products (100, 4) ['product_id', 'product_name', 'category', 'price']
orders (300, 5) ['order_id', 'customer_id', 'order_date', 'payment_method', 'order_status']
order_items (764, 5) ['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price']

In [13]:
orders["order_status"].value_counts()

order_status
completed    184
cancelled     64
refunded      52
Name: count, dtype: int64

In [22]:
#orders_status에 따른 주문 수 필터링
orders_basic = orders[['order_id', 'customer_id', 'order_date', 'order_status']]
display(orders_basic.head())

print('주문상태에 따른 주문 수')
display(orders['order_status'].value_counts())

completed_orders = orders[orders['order_status'] == 'completed']

display(completed_orders['order_status'].head())
print('completed 주문 수:', len(completed_orders))

   order_id  customer_id  order_date order_status
0         1          123  2026-07-15    completed
1         2           77  2025-09-30    cancelled
2         3          138  2026-01-27    cancelled
3         4           57  2026-04-09    cancelled
4         5          125  2026-02-28    cancelled

주문상태에 따른 주문 수

order_status
completed    184
cancelled     64
refunded      52
Name: count, dtype: int64

0     completed
5     completed
8     completed
10    completed
11    completed
Name: order_status, dtype: str

completed 주문 수: 184

In [18]:
display(products.sort_values('category', ascending=False).head(100))

    product_id product_name category   price
10          11    패션 상품 011       패션  115000
12          13    패션 상품 013       패션  164000
13          14    패션 상품 014       패션  174000
18          19    패션 상품 019       패션  108000
28          29    패션 상품 029       패션   78000
..         ...          ...      ...     ...
68          69    도서 상품 069       도서  157000
72          73    도서 상품 073       도서  114000
86          87    도서 상품 087       도서   25000
93          94    도서 상품 094       도서  124000
99         100    도서 상품 100       도서  102000

[100 rows x 4 columns]

In [24]:
order_items = order_items.copy()
order_items["line_total"] = (
    order_items["quantity"]
    * order_items["unit_price"]
)
display(order_items.head())

   order_item_id  order_id  product_id  quantity  unit_price  line_total
0              1         1         100         3      102000      306000
1              2         1          87         5       25000      125000
2              3         1           7         3      142000      426000
3              4         1           9         3      193000      579000
4              5         2          72         4      189000      756000

In [23]:
display(order_items[['order_id', 'product_id', 'quantity', 'unit_price', 'line_total']].head())

   order_id  product_id  quantity  unit_price  line_total
0         1         100         3      102000      306000
1         1          87         5       25000      125000
2         1           7         3      142000      426000
3         1           9         3      193000      579000
4         2          72         4      189000      756000

In [30]:
print('orders.order_id 중복 수:', orders['order_id'].duplicated().sum())

order_sales = order_items.merge(
    orders[['order_id', 'customer_id', 'order_date', 'order_status']],
    on='order_id',
    how='left',
    validate='many_to_one',
    indicator=True,
)

print('병합 전 행 수:', len(order_items))
print('병합 후 행 수:', len(order_sales))
display(order_sales['_merge'].value_counts())

order_sales = order_sales.drop(columns='_merge')

display(order_sales.head())

orders.order_id 중복 수: 0
병합 전 행 수: 764
병합 후 행 수: 764

_merge
both          764
left_only       0
right_only      0
Name: count, dtype: int64

,order_item_id,order_id,product_id,quantity,unit_price,line_total,customer_id,order_date,order_status
0,1,1,100,3,102000,306000,123,2026-07-15,completed
1,2,1,87,5,25000,125000,123,2026-07-15,completed
2,3,1,7,3,142000,426000,123,2026-07-15,completed
3,4,1,9,3,193000,579000,123,2026-07-15,completed
4,5,2,72,4,189000,756000,77,2025-09-30,cancelled

In [27]:
order_sales['order_date'] = pd.to_datetime(order_sales['order_date'], errors='coerce')
print('날짜 변환 실패:', order_sales['order_date'].isna().sum())

completed_order_sales = order_sales[
    order_sales['order_status'] == 'completed'
].copy()

completed_order_sales['order_month'] = (
    completed_order_sales['order_date'].dt.to_period('M').astype(str)
)

print('전체 주문 상세 행 수:', len(order_sales))
print('완료 주문 상세 행 수:', len(completed_order_sales))
print('완료 주문 매출:', completed_order_sales['line_total'].sum())

날짜 변환 실패: 0
전체 주문 상세 행 수: 764
완료 주문 상세 행 수: 474
완료 주문 매출: 148990000

In [38]:
print('products.product_id 중복 수:', products['product_id'].duplicated().sum())

completed_sales_items = completed_order_sales.merge(
    products,
    on='product_id',
    how='left',
    validate='many_to_one',
    indicator=True,
)

print('병합 전 행 수:', len(completed_order_sales))
print('병합 후 행 수:', len(completed_sales_items))
display(completed_sales_items['_merge'].value_counts())

completed_sales_items = completed_sales_items.drop(columns='_merge')

display(completed_sales_items.head())

products.product_id 중복 수: 0
병합 전 행 수: 474
병합 후 행 수: 474

_merge
both          474
left_only       0
right_only      0
Name: count, dtype: int64

,order_item_id,order_id,product_id,quantity,unit_price,line_total,customer_id,order_date,order_status,order_month,product_name,category,price
0,1,1,100,3,102000,306000,123,2026-07-15,completed,2026-07,도서 상품 100,도서,102000
1,2,1,87,5,25000,125000,123,2026-07-15,completed,2026-07,도서 상품 087,도서,25000
2,3,1,7,3,142000,426000,123,2026-07-15,completed,2026-07,도서 상품 007,도서,142000
3,4,1,9,3,193000,579000,123,2026-07-15,completed,2026-07,스포츠 상품 009,스포츠,193000
4,13,6,83,3,24000,72000,87,2026-05-29,completed,2026-05,전자기기 상품 083,전자기기,24000

In [32]:
category_sales = (
    completed_sales_items
    .groupby('category', as_index=False)
    .agg(
        total_quantity=('quantity', 'sum'),
        total_sales=('line_total', 'sum'),
    )
    .sort_values('total_sales', ascending=False)
)

category_sales['sales_ratio'] = (
    category_sales['total_sales'] / category_sales['total_sales'].sum() * 100
).round(2)

display(category_sales)

product_sales = (
    completed_sales_items
    .groupby(['product_id', 'product_name', 'category'], as_index=False)
    .agg(
        total_quantity=('quantity', 'sum'),
        total_sales=('line_total', 'sum'),
    )
    .sort_values('total_sales', ascending=False)
)

display(product_sales.head(10))

  category  total_quantity  total_sales  sales_ratio
3      스포츠             295     31743000        21.31
5     전자기기             259     26400000        17.72
2     생활용품             272     23915000        16.05
1       뷰티             223     23383000        15.69
4       식품             133     16573000        11.12
0       도서             149     16389000        11.00
6       패션             111     10587000         7.11

    product_id product_name category  total_quantity  total_sales
39          41   스포츠 상품 041      스포츠              35      5705000
11          12    식품 상품 012       식품              25      4375000
8            9   스포츠 상품 009      스포츠              20      3860000
70          72    뷰티 상품 072       뷰티              20      3780000
69          71  전자기기 상품 071     전자기기              23      3703000
66          68   스포츠 상품 068      스포츠              26      3640000
78          81  전자기기 상품 081     전자기기              22      3630000
10          11    패션 상품 011       패션              31      3565000
20          22  생활용품 상품 022     생활용품              29      3248000
86          89  생활용품 상품 089     생활용품              30      3090000

In [39]:
print(category_sales["total_sales"].sum())
print(product_sales["total_sales"].sum())

148990000
148990000

In [34]:
monthly_summary = (
    completed_order_sales
    .groupby('order_month', as_index=False)
    .agg(
        total_sales=('line_total', 'sum'),
        order_count=('order_id', 'nunique'),
    )
    .sort_values('order_month')
)

monthly_summary['average_order_value'] = (
    monthly_summary['total_sales'] / monthly_summary['order_count']
).round(0)

display(monthly_summary)

   order_month  total_sales  order_count  average_order_value
0      2025-09      2650000            5             530000.0
1      2025-10     16970000           19             893158.0
2      2025-11     11021000           13             847769.0
3      2025-12     21085000           23             916739.0
4      2026-01     14272000           16             892000.0
5      2026-02      4784000            7             683429.0
6      2026-03     18323000           25             732920.0
7      2026-04     10254000           15             683600.0
8      2026-05     16831000           19             885842.0
9      2026-06     12994000           17             764353.0
10     2026-07     10652000           15             710133.0
11     2026-08      5103000            5            1020600.0
12     2026-09      4051000            5             810200.0

In [35]:
print((monthly_summary['total_sales']).sum())

148990000

In [36]:
customer_sales = (
    completed_order_sales
    .groupby('customer_id', as_index=False)
    .agg(
        order_count=('order_id', 'nunique'),
        total_sales=('line_total', 'sum'),
    )
    .sort_values('total_sales', ascending=False)
)

customer_sales = customer_sales.merge(
    customers[['customer_id', 'city']],
    on='customer_id',
    how='left',
    validate='one_to_one',
)

customer_sales['customer_label'] = 'Customer ' + customer_sales['customer_id'].astype(str)
display(customer_sales[['customer_label', 'city', 'order_count', 'total_sales']].head(10))

  customer_label city  order_count  total_sales
0   Customer 117   성남            5      4100000
1   Customer 102   고양            4      3996000
2    Customer 83   수원            4      3880000
3    Customer 30   서울            5      3590000
4    Customer 40   서울            4      3523000
5    Customer 20   인천            2      3191000
6     Customer 3   성남            2      3178000
7   Customer 111   광주            3      3153000
8    Customer 66   서울            4      3093000
9   Customer 147   부산            2      2990000

In [37]:
print((customer_sales['total_sales']).sum())

148990000

In [40]:
print((customer_sales['total_sales']).sum())
print((monthly_summary['total_sales']).sum())
print(category_sales["total_sales"].sum())
print(product_sales["total_sales"].sum())
print('완료 주문 매출:', completed_order_sales['line_total'].sum())

148990000
148990000
148990000
148990000
완료 주문 매출: 148990000